server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.baemin.dto
  
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521
    username: system
    password: 1234

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 425426264901-jqv59qbnndgfp8qp6ibajvelh16b58j1.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email
            
          kakao:            
            client-id: 97085348d6e6eea481838fafa7dd53bd
            client-secret: iYJa7wOksgGFZHXux0W5yspJcxFkf4dW

            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: Kakao
            
          naver:
            client-id: zORABRkuXpwHnubDmYYI
            client-secret: SwScygOM0t
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

        provider:  
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id  
            
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mail :
    host : smtp.gmail.com
    port : 587
    username : welwitschias48@gmail.com
    password : kklqcauxffkwbhqg
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true

imp_key: 3807001103142846
imp_secret: LO7YdN4rGm1o6FiX2yhwaob2rJKR1bqXsGMAncZboTIWtkm9eNOfa9CBj8m1BXxlDxxLhO3bhg1SqvZz